esphome:
  name: kc868-a6

esp32:
  board: esp32dev
  framework:
    type: arduino

# Example configuration entry for ESP32
i2c:
  sda: 4
  scl: 15
  scan: true
  id: bus_a

# Pour KC868-A8 : 
  # sda: 4
  # scl: 5
# Pour KC868-A6 : 
  # sda: 4
  # scl: 15

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "blabla"

ota:
  password: "blabla"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kc868-A6 Fallback Hotspot"
    password: "blabla"

captive_portal:

# Example configuration entry
pcf8574:
  - id: 'pcf8574_hub_out_1' # for output channel 1-8
    address: 0x24
  - id: 'pcf8574_hub_in_1' # for input channel 9-16
    address: 0x22
    pcf8575: false

# Individual outputs
switch:
  - platform: gpio
    name: "light1"
    pin:
     pcf8574: pcf8574_hub_out_1
     number: 0
     mode: OUTPUT
    inverted: true
